layout: sidebar
style: light
url: "https://brunomorenobm.github.io" # the base hostname & protocol for your site


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: brunomorenobm
  # keybase: your_username
  linkedin: brunomorenobm
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Java
    web_url: https://github.com/topics/java

  - name: Python
    web_url: https://github.com/topics/python

  - name: Scala
    web_url: https://github.com/topics/scala

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes

theme: jekyll-theme-slate
